import { Card } from '../card/index.js';
export class YugiohSeries2Card extends Card<Record<string, unknown>> {
    constructor(data?: {});
    cardLeaf: null;
    nameLeaf: null;
    attributeLeaf: null;
    levelLeaf: null;
    spellTrapLeaf: null;
    imageLeaf: null;
    maskLeaf: null;
    packageLeaf: null;
    effectLeaf: null;
    descriptionLeaf: null;
    atkDefLeaf: null;
    passwordLeaf: null;
    copyrightLeaf: null;
    laserLeaf: null;
    data: {
        language: string;
        name: string;
        color: string;
        align: string;
        gradient: boolean;
        gradientColor1: string;
        gradientColor2: string;
        type: string;
        attribute: string;
        icon: string;
        image: string;
        cardType: string;
        level: number;
        monsterType: string;
        atk: number;
        def: number;
        description: string;
        firstLineCompress: boolean;
        descriptionAlign: boolean;
        descriptionZoom: number;
        descriptionWeight: number;
        package: string;
        password: string;
        copyright: string;
        laser: string;
        rare: string;
        radius: boolean;
        scale: number;
    };
    draw(): void;
    drawCard(): void;
    drawName(): void;
    drawAttribute(): void;
    drawLevel(): void;
    drawSpellTrap(): void;
    drawImage(): void;
    drawMask(): void;
    drawPackage(): void;
    drawEffect(): void;
    drawDescription(): void;
    drawAtkDef(): void;
    drawPassword(): void;
    drawCopyright(): void;
    drawLaser(): void;
    get baseImage(): string;
    get style(): {};
    get cardUrl(): string;
    get autoNameColor(): string;
    get showAttribute(): boolean;
    get attributeUrl(): string;
    get spellTrapName(): string;
    get showEffect(): string | false;
    get atkName(): string;
    get defName(): string;
}
