export declare const YUGIOH_CARD_DOCUMENT_KIND: "yugioh-card";
export declare const YUGIOH_CARD_DOCUMENT_VERSION: 1;
export declare const YUGIOH_CARD_LANGUAGES: readonly ["sc", "tc", "jp", "kr", "en", "astral", "custom1", "custom2"];
export declare const YUGIOH_CARD_TYPES: readonly ["monster", "spell", "trap", "pendulum"];
export declare const YUGIOH_MONSTER_CARD_TYPES: readonly ["normal", "effect", "ritual", "fusion", "synchro", "xyz", "link", "token"];
export declare const YUGIOH_PENDULUM_CARD_TYPES: readonly ["normal-pendulum", "effect-pendulum", "ritual-pendulum", "fusion-pendulum", "synchro-pendulum", "xyz-pendulum", "link-pendulum"];
export declare const YUGIOH_TITLE_ALIGNS: readonly ["left", "center", "right"];
export declare const YUGIOH_ARTWORK_FITS: readonly ["cover", "contain", "stretch"];
export declare const YUGIOH_EFFECT_BOX_BORDER_STYLES: readonly ["none", "default", "colored"];
export declare const YUGIOH_LAYER_SLOTS: readonly ["before-frame", "after-artwork", "before-text", "after-text", "top"];
export type YugiohCardLanguage = typeof YUGIOH_CARD_LANGUAGES[number];
export type YugiohCardType = typeof YUGIOH_CARD_TYPES[number];
export type YugiohMonsterCardType = typeof YUGIOH_MONSTER_CARD_TYPES[number];
export type YugiohPendulumCardType = typeof YUGIOH_PENDULUM_CARD_TYPES[number];
export type YugiohTitleAlign = typeof YUGIOH_TITLE_ALIGNS[number];
export type YugiohArtworkFit = typeof YUGIOH_ARTWORK_FITS[number];
export type YugiohEffectBoxBorderStyle = typeof YUGIOH_EFFECT_BOX_BORDER_STYLES[number];
export type YugiohCardLayerSlot = typeof YUGIOH_LAYER_SLOTS[number];
export type YugiohLinkArrow = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
export interface YugiohCardDocument {
    kind: typeof YUGIOH_CARD_DOCUMENT_KIND;
    version: typeof YUGIOH_CARD_DOCUMENT_VERSION;
    frame: {
        language: YugiohCardLanguage;
        font: '' | 'custom1' | 'custom2';
        type: YugiohCardType;
        attribute: string;
        icon: string;
        cardType: YugiohMonsterCardType;
        pendulumType: YugiohPendulumCardType;
        level: number;
        rank: number;
        pendulumScale: number;
        arrows: YugiohLinkArrow[];
        nameBlock: boolean;
    };
    title: {
        text: string;
        align: YugiohTitleAlign;
        fill: {
            color: string;
            gradient: boolean;
            gradientColor1: string;
            gradientColor2: string;
        };
        shadow: {
            enabled: boolean;
            color: string;
            gradient: boolean;
            gradientColor1: string;
            gradientColor2: string;
            offsetX: number;
            offsetY: number;
            opacity: number;
        };
        useRarityPreset: boolean;
    };
    artwork: {
        source: string;
        fit: YugiohArtworkFit;
    };
    foreground: {
        enabled: boolean;
        source: string;
        width: number;
        height: number;
        x: number;
        y: number;
        scale: number;
        rotation: number;
        coverLevel: boolean;
    };
    effectBox: {
        enabled: boolean;
        x: number;
        y: number;
        width: number;
        height: number;
        color: string;
        opacity: number;
        borderStyle: YugiohEffectBoxBorderStyle;
    };
    text: {
        pendulumDescription: string;
        monsterType: string;
        description: string;
        firstLineCompress: boolean;
        descriptionAlign: boolean;
        descriptionZoom: number;
        descriptionWeight: number;
        showAtkBar: boolean;
        atk: number;
        def: number;
    };
    footer: {
        package: string;
        password: string;
        copyright: string;
        laser: string;
        rare: string;
        twentieth: boolean;
        mark25th: boolean;
    };
    render: {
        radius: boolean;
        scale: number;
    };
}
export interface LegacyYugiohCardData {
    language?: string;
    font?: string;
    name?: string;
    color?: string;
    align?: string;
    gradient?: boolean;
    gradientColor1?: string;
    gradientColor2?: string;
    nameShadowColor?: string;
    nameShadowGradient?: boolean;
    nameShadowGradientColor1?: string;
    nameShadowGradientColor2?: string;
    nameShadowOffsetX?: number;
    nameShadowOffsetY?: number;
    nameShadowOpacity?: number;
    useRarityPreset?: boolean;
    type?: string;
    attribute?: string;
    icon?: string;
    image?: string;
    artworkFit?: string;
    cardType?: string;
    pendulumType?: string;
    level?: number;
    rank?: number;
    pendulumScale?: number;
    pendulumDescription?: string;
    monsterType?: string;
    atkBar?: boolean;
    atk?: number;
    def?: number;
    arrowList?: number[];
    nameBlock?: boolean;
    outFrameNameBlock?: boolean;
    outFrameNameBlockEnabled?: boolean;
    description?: string;
    firstLineCompress?: boolean;
    descriptionAlign?: boolean;
    descriptionZoom?: number;
    descriptionWeight?: number;
    package?: string;
    password?: string;
    copyright?: string;
    laser?: string;
    rare?: string;
    twentieth?: boolean;
    radius?: boolean;
    scale?: number;
    foregroundImage?: string;
    foregroundWidth?: number;
    foregroundHeight?: number;
    foregroundX?: number;
    foregroundY?: number;
    foregroundScale?: number;
    foregroundRotation?: number;
    foregroundCoverLevel?: boolean;
    effectBlockEnabled?: boolean;
    effectBlockX?: number;
    effectBlockY?: number;
    effectBlockWidth?: number;
    effectBlockHeight?: number;
    effectBlockColor?: string;
    effectBlockOpacity?: number;
    effectBlockBorder?: boolean;
    effectBlockBorderStyle?: string;
    mark25th?: boolean;
    twentyFifth?: boolean;
}
type DeepPartial<T> = {
    [K in keyof T]?: T[K] extends readonly unknown[] ? T[K] : T[K] extends object ? DeepPartial<T[K]> : T[K];
};
export declare class YugiohCardDocumentError extends Error {
    readonly path: string;
    constructor(message: string, path?: string);
}
export declare function createYugiohCardDocument(input?: DeepPartial<YugiohCardDocument>): YugiohCardDocument;
export declare function parseYugiohCardDocument(value: unknown): YugiohCardDocument;
export declare function legacyDataToYugiohCardDocument(data?: LegacyYugiohCardData, base?: YugiohCardDocument): YugiohCardDocument;
export declare function yugiohCardDocumentToLegacyData(document: YugiohCardDocument): Required<LegacyYugiohCardData>;
export {};
