import { Card } from '../card/index.js';
export class LegacyYugiohCardRenderer extends Card<Record<string, unknown>> {
    constructor(data?: {});
    cardLeaf: null;
    nameLeaf: null;
    attributeLeaf: null;
    levelLeaf: null;
    rankLeaf: null;
    spellTrapLeaf: null;
    imageLeaf: null;
    maskLeaf: null;
    pendulumLeaf: null;
    pendulumDescriptionLeaf: null;
    packageLeaf: null;
    linkArrowLeaf: null;
    effectLeaf: null;
    descriptionLeaf: null;
    atkDefLinkLeaf: null;
    passwordLeaf: null;
    copyrightLeaf: null;
    laserLeaf: null;
    rareLeaf: null;
    attributeRareLeaf: null;
    twentiethLeaf: null;
    data: {
        language: string;
        font: string;
        name: string;
        color: string;
        align: string;
        gradient: boolean;
        gradientColor1: string;
        gradientColor2: string;
        type: string;
        attribute: string;
        icon: string;
        image: string;
        cardType: string;
        pendulumType: string;
        level: number;
        rank: number;
        pendulumScale: number;
        pendulumDescription: string;
        monsterType: string;
        atkBar: boolean;
        atk: number;
        def: number;
        arrowList: never[];
        description: string;
        firstLineCompress: boolean;
        descriptionAlign: boolean;
        descriptionZoom: number;
        descriptionWeight: number;
        package: string;
        password: string;
        copyright: string;
        laser: string;
        rare: string;
        twentieth: boolean;
        radius: boolean;
        scale: number;
    };
    draw(): void;
    drawCard(): void;
    drawName(): void;
    drawAttribute(): void;
    drawLevel(): void;
    drawRank(): void;
    drawSpellTrap(): void;
    drawImage(): void;
    drawMask(): void;
    drawPendulum(): void;
    drawPendulumDescription(): void;
    drawPackage(): void;
    drawLinkArrow(): void;
    drawEffect(): void;
    drawDescription(): void;
    drawAtkDefLink(): void;
    drawPassword(): void;
    drawCopyright(): void;
    drawLaser(): void;
    drawRare(): void;
    drawAttributeRare(): void;
    drawTwentieth(): void;
    get baseImage(): string;
    get style(): {};
    get cardUrl(): string;
    get autoNameColor(): string;
    get showAttribute(): boolean;
    get attributeUrl(): string;
    get spellTrapName(): string;
    get showAttributeRare(): boolean;
    get showLevel(): boolean;
    get showRank(): boolean;
    get showEffect(): string | false;
    get showAtkDefLink(): boolean;
    get atkDefLinkUrl(): string;
}
